"""Add new fields

Revision ID: eec7bf7485a8
Revises: 
Create Date: 2023-09-11 00:42:44.070881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec7bf7485a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_list',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('spanish_word', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
